### ISSUE TITLE
Пильный станок

### ISSUE THREAD

**Issue by K14Mua** [IdealIndustrial/Ideal-Industrial-Quest-Book#11]
В главе "больше мультиблоков" стоит заменить MV пильный станок его LV версией. А квест на алмазную пластину перенести в главу к вакуумному морозильнику. И в ту же главу нужно добавить новый квест на MV пильный станок. По тому как он нужен только там. И раньше его крафтить смысла нет...

**Comment by SapientMC** [comment]
> И раньше его крафтить смысла нет
А как же алмазная Builder's wand?

**Comment by K14Morg** [comment]
> А как же алмазная Builder's wand?

Что это и зачем оно нужно?

**Comment by SapientMC** [comment]
> Что это и зачем оно нужно?

Гугл в помощ.

**Comment by KostyaKapitonov** [comment]
исправлено
...добавлен аналог ЛВ пильный станок
