### ISSUE TITLE
Хром и электролизер

### ISSUE THREAD

**Issue by K14Mua** [IdealIndustrial/Ideal-Industrial-Quest-Book#12]
В главе с вакуумным морозильником, нужно убрать жесткую зависимость крафта хрома от MV электролизера. Но сам электролизер думаю стоит оставить.

1/9 хрома можно получить в рудопромывке из рубиновой руды. В самом начале это вполне допустимая альтернатива. В будущем для промышленных масштабов конечно уже нужен MV электролизер. По этому квест на электролизер можно оставить. Или переместить куда-то вперед где ,ез него уже никак не обойстись...

**Comment by KostyaKapitonov** [comment]
исправлено
