### ISSUE TITLE
Транзистор и SMD транзистор

### ISSUE THREAD

**Issue by K14Mua** [IdealIndustrial/Ideal-Industrial-Quest-Book#13]
Добавьте в главу к вакуумному морозильника, к квсту на транзистор значение "ИЛИ"
Для крафта микросхемы нужен или обычный транзистор, или SMD транзистор.
Оба транзистора на текущем уровне развития делают одинаково просто. Но SMD делается экономней по отношению к полиэтилену.

Сделай так что б для выполнения квеста нужен был любой из двух тнанзисторов.

**Comment by KostyaKapitonov** [comment]
исправлено
