### ISSUE TITLE
Проблемы квестов

### ISSUE THREAD

**Issue by K14Mua** [IdealIndustrial/Ideal-Industrial-Quest-Book#2]
Может я не до конца понимаю идею этих кветов. Но в моем понимании, квесты должны быть путеводителем по игре. Наглядно показывать чего я достиг в игре. К чему стремиться, и чем я могу занятся в ближайщем будущем. А что в итоге? Мне не раз приходилось возвращаться и делать то что у меня уже сделано просто для того что б защитался квест.

В сборке есть много проблем. Почти все они связаны с нарушеной логикой последовательности действий, которых в моем понимании быть не должно.

К примеру "**Первая сталь**". К квесте для стали почему-то нужны паровые механизмы. Хотя ничего не мешает собрать бронзовую доменку без пара вообще. Да это будет долго и не эфективно, но все таки возможно, и именно так я и поступил. Скрафтил сталь раньше чем это предполагает квест.

**Предлагаю** разделить первую сталь и паровые мехи на отдельные не связанные квесты. Или на две отдельные ветки того же квеста. Допустим "**сталь**" и "**ефективное прозводство бронзы**".

"**Первые микросхемы**". Зачем в первых микросхемах квест на на формочки для экструндера, конкретно кольцо и капсула. Понадобятся они минимум на втором тире электромеханизмов. А это примерно после первого алюминий и хороших микросхем. **Предлагаю** убрать или переместить эти квесты на более дальний этап развития.

Напильник и строительство резервуара из реилкрафта так же предлагаю перместить, только наоборот в ранний квест к паровым мехам. Напильник это буквально второй инструмент крафта, его делают сразу после молота и он нужен для крафта железной или бронзовой кирки. В микросхемах ему не место.

Бронзовые и паровые мехи. **Предлагаю** добавить в квесты ветвление. Что б можно было выбрать, какой из двух мехов построить для дальнейшего продвижения. Или построить оба для получения наград.

"**Первый алюминий**". **Предлагаю** убрать печь сплавов которую мы уже делали. Так же предлагаю убрать центрифугу и рудопрмывку. Получить чистый алюминий можно и иным, более простым способом. Луче приберечь эти механизмы до того времени когда без них действительно не обойтись. Может сделать отдельную ветку квестов, по апгрейду паровых мехов до их электричесих аналогов? Туда и печь сплавов, и рудопромывку на замену котла с водой можно поместить.

"**Хорошая микросхема**". Предлагаю отвязать от квеста на крафт медного кабеля жидкостный экстрактор. Медный кабель можно сделать напрямую из жидкой резины. А действительно он нужен для крафта жидкого паяльного сплава для микросхем. Вот как раз со сборщиком микросхем его и нужно связать.

Надеюсь автор поймет мою мысль. Но на всякий случай напишу другими словами.
Квесты не должны тормозить развитие игрока. Они не должны показывать какой-то конкретный путь для достижения цели. Квесты должны быть гибкими, и иметь жесткие связи только там, где они действительно зависят друг от друга. Идеальным в этом отношении будет короткий квест на строительство бронзового многоблочного бойлера. Там все четко и нет ничего ненужного...

**Comment by KostyaKapitonov** [comment]
многое из этого уже пофикшено - если что пропустил и это важно - пересоздай new issue с уточнениями.
