### ISSUE TITLE
Ссылка на раздел

### ISSUE THREAD

**Issue by NNM42** [IdealIndustrial/Ideal-Industrial-Quest-Book#3]
Предложено добавлять к названию квеста аббревиатуру главы блокирующего квеста.
Как пример на светопанели ИК2 блокировку по ртути.

**Comment by KostyaKapitonov** [comment]
на самом деле таких мест не много - можно ртуть просто поближе перенести в эту же главу

**Comment by KostyaKapitonov** [comment]
ртуть перенёс, если будут еще такие места "сложные" для понимания, постараюсь переместить поближе.
