### ISSUE TITLE
Проблемы пиролизной печи

### ISSUE THREAD

**Issue by K14Mua** [IdealIndustrial/Ideal-Industrial-Quest-Book#6]
1) Предлагаю совместить вместе квест на основной блок пиролизной печи и 60 ULV каркасов для пиролизной печи.

2) Предлагаю в квест пиролизной печи добавить условие с крафтом 9 нагревательных колец без которых печь не собрать...

3) Предлагаю в квест пиролизной печи добавить условие с крафтом входных/выходных шин для предметов/жидкостей.

4) Предлагаю добавить квест на крафт микросхемы для выбора рецепта крафта пиролизной печи...

**Comment by KostyaKapitonov** [comment]
1 - нет, там теперь сделано по-другому. требуется 1 ULV каркас т.к. этот квест идёт и на пиролизку и на ULV machie Hull. Но в описании указано что для пиролизки требуется не менее 60 шт.

2 - нагревательные кольца идут и на электродоменку, так что подразумевается что игрок уже умеет и знает как крафтить нагревательные кольца,

3 - после электродоменки пользовательно уже и так должен понимать какие входные и выходные люки и шины ему нужны в зависимости от рецептов. и делать дублирующие квесты нет смысла.

4 - programmed circuit с конфигурацией? рецептов куча и как использовать пиролизку игрок должен решить сам. вводить строгие рамки не стоит, а делать квесты на все ветки это будет слишком жирно.
