### ISSUE TITLE
Проблемы с жидкой биомассой

### ISSUE THREAD

**Issue by K14Mua** [IdealIndustrial/Ideal-Industrial-Quest-Book#7]
Для выполнения квеста на ферментированную биомасу нужно обазятельно выполнить И обычную жидкую биомассу И индустриальную биомассу. Предлагаю оставить только один из вариантов. Либо совместить две биомассы в один квест со значением "или".

Предлагаю отвязать крафт газовой турбины от биомассы. Турбину обычно крафтят раньше чем топливо для нее...

**Comment by KostyaKapitonov** [comment]
ок, гляну позже
пока на паузе

**Comment by KostyaKapitonov** [comment]
оба предложения приняты, 
исправлено.
