### ISSUE TITLE
зависимость квестов главы "полиэтилен"

### ISSUE THREAD

**Issue by ko5o01gg** [IdealIndustrial/Ideal-Industrial-Quest-Book#9]
есть квест для крафта этилена. в нем три ветки на выбор. одна из древесного газа. собственно судя логике квестов надо сначала скрафтить "продвинутый дистилятор", а уже потом "древесный газ". я изначально подумал что сам древесный газ крафтится в дистиляторе (такой крафт есть из "разлитого" древесного угля), но мне объяснили что из древесного газа в том самом дистиляторе надо крафтить "Этилен". а сам древесный газ давно можно получать в пиролизной печи. посему я предлагаю в квестах поменять зависимость . СНАЧАЛА должен быть древесный газ, а потом уже "дистилятор". надеюсь меня поймут и рассмотрят предложение

**Comment by KostyaKapitonov** [comment]
исправлено
